services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - VITE_API
      - VITE_IS_DEV=false
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
    restart: always